spring.application.name=QuantityMeasurementApplication

# H2 In-Memory Database
spring.datasource.url=jdbc:postgresql://localhost:5432/quantitydb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Post#123@gre

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Schema Initialization
# Tell Spring Boot to run our schema.sql on startup
spring.sql.init.mode=never
#spring.sql.init.schema-locations=classpath:db/schema.sql

# H2 Web Console (http://localhost:8080/h2-console)
#spring.h2.console.enabled=false
#spring.h2.console.path=/h2-console

# Server
server.port=8080

# Logging 
logging.level.com.apps.quantitymeasurement=INFO
logging.level.org.springframework.web=DEBUG

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=email,profile

# JWT
app.jwt.secret=
app.jwt.expiration-ms=86400000

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method